version: "3.7"

services:

  loginservice_api:
    build: .
    environment:
      NODE_ENV: development
      PORT: 3003
      PGHOST: db
      PGUSER: dbuser
      PGDATABASE: bookstore
      PGPASSWORD: dbpass
      PGPORT: 54321
    ports:
      - "3003:3003"
    networks:
      - lab5network

networks:
  lab5network: