version: "3.7"

services:

  loginservice_api:
    build: .
    environment:
      NODE_ENV: development
      PORT: 3003
      PGHOST: database_db_1
      PGUSER: dbuser
      PGDATABASE: bookstore
      PGPASSWORD: dbpass
      PGPORT: 5432
      JWT_SECRET_KEY: myawesomeultrasecretkey
      JWT_ISSUER: 'pw backend'
      JWT_SUBJECT: 'pw'
      JWT_AUDIENCE: 'pw client'
    ports:
      - "3003:3003"

networks:
  default:
    external: true
    name: database_lab5network