version: "3.7"

services:

  appservice_api:
    build: .
    environment:
      NODE_ENV: development
      PORT: 3002
      PGHOST: db
      PGUSER: dbuser
      PGDATABASE: bookstore
      PGPASSWORD: dbpass
      PGPORT: 54321
      JWT_SECRET_KEY: myawesomeultrasecretkey
      JWT_ISSUER: 'pw backend'
      JWT_SUBJECT: 'pw'
      JWT_AUDIENCE: 'pw client'
    ports:
      - "3002:3002"
    networks:
      - lab5network

networks:
  lab5network: