version: "3.7"

services:

  appservice_api:
    build: .
    environment:
      NODE_ENV: development
      PORT: 3002
      PGHOST: database_db_1
      PGUSER: dbuser
      PGDATABASE: performanceapp
      PGPASSWORD: dbpass
      PGPORT: 5432
      JWT_SECRET_KEY: myawesomeultrasecretkey
      JWT_ISSUER: 'pw backend'
      JWT_SUBJECT: 'pw'
      JWT_AUDIENCE: 'pw client'
      BUSINESSHOST: businesslogicservice_measure_performance_py_1
    ports:
      - "3002:3002"

networks:
  default:
    external: true
    name: database_lab5network