version: "3.7"

services:

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "30001:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: test
    networks:
      - lab5network
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    hostname: database_pgadmin_1
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure

  db:
    image: postgres
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
      POSTGRES_DB: book1
      TZ: Europe/Bucharest
      PGTZ: Europe/Bucharest
    ports:
      - "5432:5432"
    volumes:
      - lab6_pgdb:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - lab5network
    hostname: database_db_1
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
     
      
  loginservice-api:
    image: myimg_3:latest
    ports:
      - "3004:3004"
    networks:
      - lab5network
    #depends_on:
    #  - 'db'
    #env_file: ./.env
    hostname: database_loginservice-api_1
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
    environment:
      NODE_ENV: development
      PORT: 3004
      PGHOST: database_db_1
      PGUSER: dbuser
      PGDATABASE: book1
      PGPASSWORD: dbpass
      PGPORT: 5432
      JWT_SECRET_KEY: myawesomeultrasecretkey
      JWT_ISSUER: 'pw backend'
      JWT_SUBJECT: 'pw'
      JWT_AUDIENCE: 'pw client'

volumes:
  lab6_pgdb:
  pgadmin-data:
  
networks:
  lab5network:
#    driver: overlay

